### ISSUE TITLE
fail build with miniupnp 2.0

### ISSUE THREAD

**Issue by sl1pkn07** [dinoex/iroffer-dinoex#7]
```
gcc -c -Isrc -I/usr/include -I/usr/include -I/usr/include -I/usr/include/ruby-2.3.0 -I/usr/include/ruby-2.3.0/x86_64-linux -I/usr/include/ruby-2.3.0/x86_64-linux -Wall -march=native -O2 -pipe -fstack-protector-strong -o o.en/upnp.o src/upnp.c
src/upnp.c: In function 'init_upnp':
src/upnp.c:89:13: error: too few arguments to function 'miniwget'
   descXML = miniwget(dev->descURL, &descXMLsize, 0);
             ^~~~~~~~
In file included from src/upnp.c:44:0:
/usr/include/miniupnpc/miniwget.h:19:25: note: declared here
 MINIUPNP_LIBSPEC void * miniwget(const char *, int *, unsigned int, int *);
                         ^~~~~~~~
make: *** [Makefile:173: o.en/upnp.o] Error 1
```

**Comment by dinoex** [comment]
Thanks for the Report, Issue fixed in Source.
